/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#cfbcff",
        "primary": "#cfbcff",
        "outline-variant": "#494551",
        "on-primary-fixed-variant": "#4f378a",
        "inverse-primary": "#6750a4",
        "on-secondary-fixed-variant": "#4b4263",
        "on-error": "#690005",
        "surface-container-highest": "#36343a",
        "inverse-surface": "#e6e0e9",
        "primary-fixed": "#e9ddff",
        "error": "#ffb4ab",
        "tertiary-fixed": "#ffdf93",
        "secondary-fixed": "#e9ddff",
        "on-background": "#e6e0e9",
        "primary-container": "#6750a4",
        "surface-container-low": "#1d1b20",
        "tertiary-container": "#c9a74d",
        "surface-dim": "#141218",
        "on-tertiary-fixed-variant": "#594400",
        "surface-variant": "#36343a",
        "background": "#141218",
        "secondary": "#cdc0e9",
        "outline": "#948e9c",
        "surface-tint": "#cfbcff",
        "inverse-on-surface": "#322f35",
        "surface-container-lowest": "#0f0d13",
        "surface-container": "#211f24",
        "on-secondary-fixed": "#1f1635",
        "on-secondary": "#342b4b",
        "on-primary-container": "#e0d2ff",
        "surface-container-high": "#2b292f",
        "on-surface-variant": "#cbc4d2",
        "tertiary": "#e7c365",
        "on-tertiary-container": "#503d00",
        "on-tertiary-fixed": "#241a00",
        "secondary-fixed-dim": "#cdc0e9",
        "on-surface": "#e6e0e9",
        "tertiary-fixed-dim": "#e7c365",
        "on-secondary-container": "#bfb2da",
        "on-error-container": "#ffdad6",
        "on-tertiary": "#3e2e00",
        "secondary-container": "#4d4465",
        "surface-bright": "#3b383e",
        "on-primary": "#381e72",
        "on-primary-fixed": "#22005d",
        "surface": "#141218",
        "error-container": "#93000a"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "unit": "4px",
        "container-padding": "32px",
        "sm": "8px",
        "lg": "24px",
        "xs": "4px",
        "gutter": "16px",
        "md": "16px",
        "xl": "48px"
      },
      fontFamily: {
        "body-main": ["Inter"],
        "h1": ["Inter"],
        "h2": ["Inter"],
        "label-caps": ["Inter"],
        "body-muted": ["Inter"],
        "code-block": ["JetBrains Mono"]
      },
      fontSize: {
        "body-main": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "h1": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "h2": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-muted": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "code-block": ["13px", { lineHeight: "20px", fontWeight: "400" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
    require('@tailwindcss/typography'),
  ],
  darkMode: 'class',
}
